module VerifyExamples.MARKDOWN.README.Test_2_0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bytes.Encode.Extra
import Bytes.Encode as Encode
import Bytes.Decode.Extra exposing (andMap, hardcoded)
import Bytes.Decode as Decode exposing (Decoder)
import Bytes.Extra
import Bytes exposing (Bytes, Endianness(..))

type MyData2 = MyData2 Int Int Int Int Int Int Int Int
type alias MyData =
  { count : Int
  , title : String
  , status : Status
  , weighting : Float
  }
type Status = Downloaded | Downloading | ToFetch | NotUploaded

myData2Decoder : Decoder MyData2
myData2Decoder =
    Bytes.Decode.Extra.map8 MyData2
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
myDataDecoder : Decoder MyData
myDataDecoder =
    Decode.succeed MyData
        |> andMap (Decode.unsignedInt16 BE)
        |> andMap (Decode.unsignedInt16 BE |> Decode.andThen Decode.string)
        |> hardcoded Downloaded
        |> andMap (Decode.float64 BE)
stringToBytes : String -> List Int
stringToBytes =
    Encode.string >> Encode.encode >> Bytes.Extra.toByteValues



spec2 : Test.Test
spec2 =
    Test.test "Documentation VerifyExamples: \n\n    stringToBytes \"Hello world!\"\n    --> [ 0x48, 0x65, 0x6c, 0x6c\n    --> , 0x6f, 0x20, 0x77, 0x6f\n    --> , 0x72, 0x6c, 0x64, 0x21\n    --> ]" <|
        \() ->
            Expect.equal
                (
                stringToBytes "Hello world!"
                )
                (
                [ 0x48, 0x65, 0x6c, 0x6c
                , 0x6f, 0x20, 0x77, 0x6f
                , 0x72, 0x6c, 0x64, 0x21
                ]
                )