module VerifyExamples.MARKDOWN.README.Test_0_0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Bytes.Encode.Extra
import Bytes.Encode as Encode
import Bytes.Decode.Extra exposing (andMap, hardcoded)
import Bytes.Decode as Decode exposing (Decoder)
import Bytes.Extra
import Bytes exposing (Bytes, Endianness(..))

type MyData2 = MyData2 Int Int Int Int Int Int Int Int
type alias MyData =
  { count : Int
  , title : String
  , status : Status
  , weighting : Float
  }
type Status = Downloaded | Downloading | ToFetch | NotUploaded

myData2Decoder : Decoder MyData2
myData2Decoder =
    Bytes.Decode.Extra.map8 MyData2
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
        (Decode.unsignedInt16 LE) (Decode.unsignedInt16 LE)
myDataDecoder : Decoder MyData
myDataDecoder =
    Decode.succeed MyData
        |> andMap (Decode.unsignedInt16 BE)
        |> andMap (Decode.unsignedInt16 BE |> Decode.andThen Decode.string)
        |> hardcoded Downloaded
        |> andMap (Decode.float64 BE)
stringToBytes : String -> List Int
stringToBytes =
    Encode.string >> Encode.encode >> Bytes.Extra.toByteValues



spec0 : Test.Test
spec0 =
    Test.test "Documentation VerifyExamples: \n\n    Decode.decode myData2Decoder <|\n        Encode.encode <| Bytes.Encode.Extra.list (Encode.unsignedInt16 LE) [1, 2, 3, 4, 5, 6, 7, 8]\n    --> Just (MyData2 1 2 3 4 5 6 7 8)" <|
        \() ->
            Expect.equal
                (
                Decode.decode myData2Decoder <|
                    Encode.encode <| Bytes.Encode.Extra.list (Encode.unsignedInt16 LE) [1, 2, 3, 4, 5, 6, 7, 8]
                )
                (
                Just (MyData2 1 2 3 4 5 6 7 8)
                )